include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - avoid_multiple_declarations_per_line
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - file_names
    - camel_case_extensions
    - camel_case_types
    - exhaustive_cases
    - no_duplicate_case_values
    - prefer_relative_imports
  
